INSERT INTO tasks (judul_tugas,
                   deskripsi_tugas,
                   tenggat_tugas,
                   tingkat_kesulitan,
                   status)
VALUES ('Belajar Polimorfisme',
        'Siapkan contoh kode polimorfisme untuk presentasi OOP.',
        NOW() + INTERVAL '1 day',
        'SEDANG',
        'BELUM_SELESAI'),
       ('UI Mockup Pomodoro',
        'Desain tata letak tampilan utama aplikasi pomodoro.',
        NOW() + INTERVAL '3 days',
        'MUDAH',
        'BELUM_SELESAI'),
       ('Refactor Timer Engine',
        'Perbaiki arsitektur engine timer agar lebih modular.',
        NOW() - INTERVAL '6 hours',
        'SULIT',
        'TERLAMBAT'),
       ('Publikasi Release Alpha',
        'Rilis versi alpha ke internal tester setelah regression test.',
        NULL,
        'SEDANG',
        'BELUM_SELESAI')
ON CONFLICT DO NOTHING;
